name: Required QA Approval
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  check-qa-approval:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
    - name: Pass for main branch
      if: github.ref == 'refs/heads/main'
      run: echo "Main branch detected, passing without checks."
      # - name: Check if required label was added by specific user
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const pr = context.payload.pull_request;
      #       const prAuthor = pr.user.login;
      #       const prNumber = pr.number;
      #       const owner = context.repo.owner;
      #       const repo = context.repo.repo;

      #       const requiredLabel = 'QA Approved';

      #       const currentLabels = pr.labels.map(label => label.name);
      #       if (!currentLabels.includes(requiredLabel)) {
      #         core.setFailed(`Label "${requiredLabel}" is not currently present on the PR.`);
      #         return;
      #       }

      #       let allEvents = [];

      #       for await (const { data: events } of github.paginate.iterator(
      #         github.rest.issues.listEventsForTimeline,
      #         {
      #           owner,
      #           repo,
      #           issue_number: prNumber,
      #           per_page: 100,
      #         }
      #       )) {
      #         allEvents = allEvents.concat(events);
      #       }

      #       // Find if the label was added by someone other than the PR author
      #       const labelEvent = allEvents.reverse().find(event =>
      #         event.event === 'labeled' &&
      #         event.label?.name === requiredLabel
      #       );

      #       if (labelEvent){
      #         if (labelEvent.actor.login === prAuthor) {
      #           core.setFailed(`The "${requiredLabel}" label was added by the PR author (${prAuthor}). It must be added by someone else.`);
      #           return;
      #         }else{
      #           console.log(`The "${requiredLabel}" label was correctly added by ${labelEvent.actor.login}.`);
      #         }
      #       }