name: Deploy on specific branch merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' && github.event.pull_request.head.ref == 'release-candidate'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags

      - name: Create and push tag
        run: |
          CURRENT_VERSION=$(cat version.txt)
          git tag ${CURRENT_VERSION}
          git push origin ${CURRENT_VERSION}

          gh release create ${CURRENT_VERSION} --title "Release ${CURRENT_VERSION}" --notes "Automated release."

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main to develop
        run: |
          gh pr create --title "Release ${CURRENT_VERSION}" --body "Merge from main to develop" --head main --base develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}