name: Create new release 🚀

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-release:
    name: Create release-candidate and PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 1️⃣ Create release-candidate from main
      - name: Create release-candidate branch
        run: |
          git checkout main
          git pull origin main
          git checkout -b release-candidate
          git push origin release-candidate --force

      # 2️⃣ Create proposed-release-changes from development and bump version
      - name: Create proposed-release-changes branch
        run: |
          git checkout development
          git pull origin development
          git checkout -b proposed-release-changes
          
          # Bump version in pubspec.yaml (patch increment)
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          IFS='.' read -r major minor patch <<< "${current_version%%+*}"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i "s/^version: .*/version: $new_version/" pubspec.yaml

          git add pubspec.yaml
          git commit -m "chore: bump version to $new_version"
          
          git push origin proposed-release-changes --force
          

      # 3️⃣ Create PR proposed-release-changes -> release-candidate
      - name: Create PR (proposed-release-changes → release-candidate)
        run: gh pr create -B release-candidate -H proposed-release-changes --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Create PR release-candidate -> main
      - name: Create PR (release-candidate → main)
        run: gh pr create -B main -H release-candidate --title 'Merge release-candidate into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
