name: Create new release 🚀

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-release:
    name: Create release-candidate proposal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 2️⃣ Create proposed-release-candidate from development and bump version
      - name: Create proposed-release-candidate branch
        run: |
          git checkout development
          git pull origin development
          git checkout -b proposed-release-candidate

          # Bump version in pubspec.yaml (patch increment)
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          IFS='.' read -r major minor patch <<< "${current_version%%+*}"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i "s/^version: .*/version: $new_version/" pubspec.yaml

          git add pubspec.yaml
          git commit -m "chore: bump version to $new_version"
          
          git push origin proposed-release-candidate --force  
      
      # Create PR proposed-release-changes -> release-candidate
      - name: Create PR (proposed-release-changes → release-candidate)
        run: |
          # Close existing PR if it exists
          existing_pr=$(gh pr list -B release-candidate -H proposed-release-changes --json number --jq '.[0].number')
          if [ -n "$existing_pr" ]; then
            gh pr close "$existing_pr"
          fi
          gh pr create -B release-candidate -H proposed-release-changes --title 'New release proposal: XX.YY.ZZ' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}