## This workflow when the version on main is updated, it creates a tag and a release, and creates a PR to merge main back to development.
name: Deploy on specific branch merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'version.txt'
  
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          

      - name: Create and push tag
        run: |
          git fetch --tags
          
          CURRENT_VERSION=$(cat version.txt)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          
          git tag ${CURRENT_VERSION}
          git push origin ${CURRENT_VERSION}

          gh release create ${CURRENT_VERSION} --title "Release ${CURRENT_VERSION}" --notes "Automated release."

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main to development
        run: |
          gh pr create --title "Merge ${CURRENT_VERSION} from main to development" --body "Merge from main to development" --head main --base development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}