## This workflow is triggered every time there is a push to release-candidate branch.
## This automatically generates the builds via fastlane and creates a PR to main branch.
name: Merge changes to release-candidate and generate build

on:
  push:
    branches:
      - release-candidate

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-release:
    name: Create ongoing release-candidate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create PR (release-candidate → main)
        run: |
          # Close existing PR if it exists
          existing_pr=$(gh pr list -B main -H release-candidate --json number --jq '.[0].number')
          if [ -n "$existing_pr" ]; then
            gh pr close "$existing_pr"
          fi
          
          CURRENT_VERSION=$(cat version.txt)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          ./scripts/generate_changelog.sh release-candidate main

          gh pr create -B main -H release-candidate --title "Release: $CURRENT_VERSION in progress." --body $'Merge this PR when the release is stable for 100% of the users. \n \n This release contains: \n \n'"$(cat changelog.txt)"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      # Run fastlane
      - name: Run fastlane release-candidate
        ## Replace with your fastlane action
        run: |
          echo "Running fastlane for release-candidate..."