name: Auto Merge Main to Develop

on:
  pull_request:
    types: [review_requested, submitted, labeled, synchronize, opened, reopened]
    branches:
      - development

jobs:
  auto-merge:
    if: github.base_ref == 'development' && github.head_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check PR approvals
        id: approvals
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approved = reviews.data.filter(r => r.state === 'APPROVED');
            const requiredApprovals = 1; // Change as needed
            if (approved.length >= requiredApprovals && pr.data.mergeable_state === 'clean') {
              core.setOutput('can_merge', 'true');
            } else {
              core.setOutput('can_merge', 'false');
            }

      - name: Merge PR
        if: steps.approvals.outputs.can_merge == 'true'
        run: gh pr merge "$GITHUB_HEAD_REF" --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}