name: Require Label from Specific User

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened, edited]

jobs:
  check-label-author:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Check if required label was added by specific user
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const requiredLabel = 'QA Passed'; // change this
            const requiredUser = 'pietroid'; // change this

            const events = await github.paginate(
              github.rest.issues.listEventsForTimeline,
              {
                owner,
                repo,
                issue_number: prNumber,
              }
            );

            const labelEvent = events.find(event =>
              event.event === 'labeled' &&
              event.label?.name === requiredLabel &&
              event.actor?.login === requiredUser
            );

            if (!labelEvent) {
              core.setFailed(`The label "${requiredLabel}" must be added by "${requiredUser}".`);
            } else {
              console.log(`✅ Label "${requiredLabel}" was added by "${requiredUser}".`);
            }