name: Require Label from Specific User

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened, edited]

jobs:
  check-label-author:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Check if required label was added by specific user
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const prAuthor = pr.user.login;
            const prNumber = pr.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const requiredLabel = 'QA Approved';

            // Get timeline events
            const events = await github.paginate(
              github.rest.issues.listEventsForTimeline,
              {
                owner,
                repo,
                issue_number: prNumber,
              }
            );

            // Find if the label was added by someone other than the PR author
            const labelEvent = events.find(event =>
              event.event === 'labeled' &&
              event.label?.name === requiredLabel &&
              event.actor?.login !== prAuthor
            );

            if (!labelEvent) {
              core.setFailed(`The "${requiredLabel}" label must be added by someone other than the PR author (${prAuthor}).`);
            } else {
              console.log(`✅ Label "${requiredLabel}" was added by ${labelEvent.actor.login}.`);
            }